apiVersion: v1
kind: Service
metadata:
  name: {{ include "jeju-da.fullname" . }}
  labels:
    {{- include "jeju-da.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.da.port }}
      targetPort: da
      protocol: TCP
      name: da
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "jeju-da.selectorLabels" . | nindent 4 }}












