# Blockscout - Testnet Overrides

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:502713364895:certificate/34c89eb5-a94f-406a-be3c-c40008f4f693"
  hosts:
    - host: explorer.testnet.jejunetwork.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: blockscout-testnet-tls
      hosts:
        - explorer.testnet.jejunetwork.org

config:
  subnetwork: "Testnet"
  chainId: 420690
  ethereum:
    jsonRpcUrl: "http://reth-archive.rpc.svc.cluster.local:8545"
    traceUrl: "http://reth-archive.rpc.svc.cluster.local:8545"
    wsUrl: "ws://reth-archive.rpc.svc.cluster.local:8546"
  rollup:
    l1RpcUrl: "http://geth-l1.l1.svc.cluster.local:8545"
