# Blockscout - Mainnet Overrides
# NOTE: Enable ingress + set certificate ARN/hostnames when mainnet domain is finalized.

ingress:
  enabled: false

config:
  subnetwork: "Mainnet"
  chainId: 420691
  ethereum:
    jsonRpcUrl: "http://reth-archive.rpc.svc.cluster.local:8545"
    traceUrl: "http://reth-archive.rpc.svc.cluster.local:8545"
    wsUrl: "ws://reth-archive.rpc.svc.cluster.local:8546"
  rollup:
    l1RpcUrl: "http://geth-l1.l1.svc.cluster.local:8545"
