apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "op-supervisor.fullname" . }}
  labels:
    {{- include "op-supervisor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "op-supervisor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "op-supervisor.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: op-supervisor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --datadir={{ .Values.config.datadir }}
            - --rpc.addr={{ .Values.config.rpc.addr }}
            - --rpc.port={{ .Values.config.rpc.port }}
            {{- if .Values.config.metrics.enabled }}
            - --metrics.enabled
            - --metrics.addr={{ .Values.config.metrics.addr }}
            - --metrics.port={{ .Values.config.metrics.port }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.rpc.port }}
              name: rpc
            - containerPort: {{ .Values.service.metrics.port }}
              name: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}












