apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-supervisor.fullname" . }}
  labels:
    {{- include "op-supervisor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpc.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "op-supervisor.selectorLabels" . | nindent 4 }}












