[package]
name = "token-transfer"
version = "0.1.0"
edition = "2021"
description = "ZK proof of token transfer inclusion"

[dependencies]
sp1-zkvm = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }

[[bin]]
name = "token_transfer"
path = "src/main.rs"
