[workspace]
members = [
    "ed25519",
    "consensus",
    "ethereum",
    "state",
    "solana-consensus",
    "token-transfer",
]
resolver = "2"

[workspace.dependencies]
sp1-zkvm = "4.0"
sp1-derive = "4.0"
sha2 = "0.10"
sha3 = "0.10"
ed25519-dalek = "2.1"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.0"
