{{- if .Values.bot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crucible.fullname" . }}-bot
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4020
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 4021
      targetPort: a2a
      protocol: TCP
      name: a2a
    - port: 4022
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "crucible.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bot
{{- end }}
