# Gateway - Testnet Configuration

image:
  repository: 502713364895.dkr.ecr.us-east-1.amazonaws.com/jeju/gateway
  tag: "testnet-latest"

replicaCount: 2

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:502713364895:certificate/0a915a42-9da2-4133-af16-ac7080d23308"
  hosts:
    - host: gateway.testnet.jeju.network
      paths:
        - path: /
          pathType: Prefix
    - host: gateway.testnet.jeju.network
      paths:
        - path: /
          pathType: Prefix

env:
  - name: NEXT_PUBLIC_NETWORK
    value: "testnet"
  - name: NEXT_PUBLIC_CHAIN_ID
    value: "420690"
  - name: NEXT_PUBLIC_RPC_URL
    value: "https://testnet-rpc.jeju.network"
  - name: BUNDLER_URL
    value: "https://bundler.testnet.jeju.network"
  - name: INDEXER_URL
    value: "https://indexer.testnet.jeju.network/graphql"

