services:
  db:
    container_name: squid-db-1
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT:-23798}:5432"
    shm_size: 1gb
