apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "op-dispute-mon.fullname" . }}
  labels:
    {{- include "op-dispute-mon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "op-dispute-mon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "op-dispute-mon.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: op-dispute-mon
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["op-dispute-mon"]
          args:
            - "--l1-eth-rpc={{ .Values.config.l1.rpcUrl }}"
            - "--rollup-rpc={{ .Values.config.rollup.rpcUrl }}"
            {{- if and .Values.config.gameFactory .Values.config.gameFactory.address (ne .Values.config.gameFactory.address "0x0000000000000000000000000000000000000000") }}
            - "--game-factory-address={{ .Values.config.gameFactory.address }}"
            {{- end }}
            {{- if .Values.config.metrics.enabled }}
            - "--metrics.enabled"
            - "--metrics.addr={{ .Values.config.metrics.addr }}"
            - "--metrics.port={{ .Values.config.metrics.port }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.metrics.port }}
              name: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}













