[package]
name = "jeju-launchpad"
version = "0.1.0"
description = "Jeju Network Token Launchpad for Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jeju_launchpad"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
init-if-needed = ["anchor-lang/init-if-needed"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }

